---
# tasks file for orchestrator
- name: Copy files
  ansible.builtin.copy:
    src: .
    dest: .
    directory_mode: 

- name: Git get server
  become: true
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ repo }}"
    single_branch: yes
    version: "{{ branch }}"

- name: Setup systemd 
  ansible.builtin.copy:
    src: myapp.service
    dest: /etc/systemd/system/myapp.service

- name: Reboot systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable service 
  ansible.builtin.systemd_service:
    name: myapp
    enabled: true

- name: Start service 
  ansible.builtin.systemd_service:
    name: myapp
    state: restarted